### ISSUE TITLE
Running in a fresh VM, GimelStudio was able to create it's config folder, but not the config file. 

### ISSUE THREAD

**Issue by instance-id** [GimelStudio/GimelStudio#124] opened 2021-12-07 01:34 UTC
**Describe the bug**
When I was doing testing in the fresh VM, after building and attempting to run the application for the first time, it seems it was able to create ~/.gimelstudio/ but it was not able to create the config file itself.

<details>
<summary>Terminal output</summary>

```sh
10075 INFO: Removing dir /home/mosthated/dev/github/GimelStudio/dist/GimelStudio
10135 INFO: Building COLLECT COLLECT-00.toc
10446 INFO: Building COLLECT COLLECT-00.toc completed successfully.
Build complete. Run GimelStudio now? y/n y
mosthated@pop-os:~/dev/github/GimelStudio$ [INFO] Registered core nodes
[INFO] Registered custom nodes
Traceback (most recent call last):
  File "main.py", line 67, in OnInit
AttributeError: 'NoneType' object has no attribute 'upper'
OnInit returned false, exiting...

```
</details>

I tried it a second time, starting it directly instead of letting the build script start it, just in case that has anything to do with it, but it had the same results.

<details>
<summary>Terminal output - second try</summary>

```sh
mosthated@pop-os:~/dev/github/GimelStudio/dist/GimelStudio$ ./GimelStudio 
[INFO] Registered core nodes
[INFO] Registered custom nodes
Traceback (most recent call last):
  File "main.py", line 67, in OnInit
AttributeError: 'NoneType' object has no attribute 'upper'
OnInit returned false, exiting...

```

</details>

Once I manually created the config file by just copying it from my desktop into the VM's ~/.gimelstudio/pr1-config.json, it fired up just fine.

I didn't have this issue with my desktop. Upon first run, it created the folder and config file. The only real difference between the environments is my desktop was using pyenv to create the build and not the system install of py3, like the VM.  I am wondering if since pyenv is installed and ran from  $HOME/.pyenv/bin/, it might have something to do with it, but I feel like the built application, after the fact, it would not matter?

**To Reproduce**
From a fresh VM, navigate to dist/GimelStudio and execute the application via:  ./GimelStudio
If you create a config manually in ~/.gimelstudio/pr1-config.json, then start it again, it works.
If you then remove/rename the config, ex. pr1-config.json.bak and try to start it again, it no longer works.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Issue does occur on:

<details>
<summary>VM with issue</summary>

```sh
python3 -V : Python 3.9.5
which python3: /usr/bin/python3

OS: Pop!_OS 21.04 x86_64 
Host: KVM/QEMU (Standard PC (Q35 + ICH9, 2009) pc-q35-5.2) 
Kernel: 5.15.5-76051505-generic 
Uptime: 39 mins 
Packages: 1910 (dpkg) 
Shell: bash 5.1.4 
Resolution: 1504x729 
DE: GNOME 3.38.4 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD EPYC-Rome (24) @ 3.493GHz 
GPU: 00:01.0 Red Hat, Inc. QXL paravirtual graphic card 
Memory: 1439MiB / 15620MiB 

```

</details>

Issue does not occur on:

<details>
<summary>Desktop system without issue</summary>

```sh
pyenv 2.2.1
pyenv python version: python3.9.9
whereis pyenv  - /home/mosthated/.pyenv/bin/pyenv

OS: Pop!_OS 21.04 x86_64
Host: X570 AORUS ELITE -CF
Kernel: 5.13.0-7620-generic
Uptime: 6 days, 21 hours, 10 mins
Packages: 3559 (dpkg), 171 (brew), 63 (flatpak), 13 (snap)
Shell: zsh 5.8
Resolution: 1920x1080, 2560x1080, 1920x1080
DE: GNOME 3.38.4
WM: Mutter
WM Theme: Pop
Theme: Materia-dark-compact [GTK2/3]
Icons: Flatery-Orange-Dark [GTK2/3]
Terminal: alacritty
CPU: AMD Ryzen 9 3950X (32) @ 3.500GHz
GPU: NVIDIA GeForce RTX 2070
Memory: 44962MiB / 64250MiB

```

</details>
 
**Additional context**
I am going to install pyenv in the VM and then build with that and see if there is any sort of difference in behavior with the final application, I would not think there would be, but I guess that is what testing is all about.

**Comment by Correct-Syntax** [comment] 2021-12-07 01:38
@instance-id thanks for reporting this. 👍  

I had noticed a similar issue before and notified @iwoithe who is kindly working on this. @iwoithe you definately have confirmation on this one. 😄

**Comment by iwoithe** [comment] 2021-12-07 06:15
@instance-id Thanks for the in-depth bug report. It is much appreciated. :slightly_smiling_face:

**Comment by iwoithe** [comment] 2021-12-07 06:35
Slight problem: I can't actually recreate this on Windows 10. When I run ``python main.py``, it creates both the ``.gimelstudio`` directory and the config file.

**Steps to reproduce**
1. Manually delete the ``~/.gimelstudio`` directory
2. Open a terminal and navigate to the ``src`` directory of Gimel Studio
3. Run ``python main.py``

I will also mention that the preferences dialog works how it's meant to (reads and writes to the config file correctly).

**Comment by Correct-Syntax** [comment] 2021-12-07 21:00
@iwoithe I just reproduced it by doing the following:

1. Manually delete the ``~/.gimelstudio`` directory
2. Run the .exe file (you can use the one in the Github releases)
3. The ``.gimelstudio`` folder is created but the config file is not (and Gimel Studio doesn't start).

Since the difference is that I ran it via the .exe, it seems there is something awry with it when it is bundled. 

Is it possible that the default_config file is not seen once the exe is generated via PyInstaller because it is in the ``datafiles`` folder which gets zipped?

**Comment by iwoithe** [comment] 2021-12-08 04:01
Closing this issue as https://github.com/GimelStudio/GimelStudio/commit/4df21ad9f7eefc2a76bf8dd770dd86b479e0afbd fixes it

**Closed by iwoithe** 2021-12-08 04:01 UTC
Labels: bug

**Comment by instance-id** [comment] 2021-12-08 06:00
That's great news that it's figured out. The only thing, though, is that portion of the build script would only deal with Windows. This particular issue I opened was technically for Linux, I didn't have a Windows machine at the time (I have one setup now). I can certainly try out the change you made, though, and update it accordingly if the end result is the same. :+1:

**Comment by iwoithe** [comment] 2021-12-08 07:15
> I opened was technically for Linux [...] I can certainly try out the change you made

I tested this successfully on Windows 10. :slightly_smiling_face:

**Comment by Correct-Syntax** [comment] 2021-12-08 14:41
Maybe a more portable solution would be to add the default_json contents to a .py file so that it is bundled with the application rather than a separate .json file.
